---

- name: Install docker-py
  pip:
    name: docker-py
    version : "{{dockerpy_version}}"
  become: yes

- docker_login:
    username: "{{item.username}}"
    password: "{{item.password}}"
    email: "{{item.email | default(omit)}}"
    registry_url: "{{item.url}}"
  with_items: "{{docker_registries}}"
  become: yes
